# Deal with the desire of interrupting successfully a plan at an intermediate step, 
# Mark the actions of the plan that should be executed as committed and execute a valid sequence of only them
# If not a valid sequence, request won't be accepted

Plan committed_plan
---
bool accepted