planner:
  ros__parameters:
    plan_solver_plugins: ["POPF", "plansys2/POPFPlanSolver"]
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"
    JAVAFF:
      plugin: "plansys2/JavaFFPlanSolver"
